# Generated by Django 6.1.1 on 2026-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_category_alter_livro_autor_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='books', to='biblioteca.category'),
        ),
    ]
