# Generated by Django 6.1.1 on 2026-10-10 13:23

from django.db import migrations


def copiar_autores(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')

    for livro in Livro.objects.all():
        if livro.autor_id:
            livro.autores.add(livro.autor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_livro_autores'),
    ]

    operations = [
        migrations.RunPython(copiar_autores),
    ]