# Generated by Django 6.1.1 on 2026-10-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20261010_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
    ]
